# Adjust for your hostnames, run this playbook with -vvvv and look at the SSH
# connections ansible makes.

- hosts: main
  tasks:
    - name: broken
      shell: ls
      delegate_to: "{{ item }}"
      with_items: "{{ groups.other }}"
    - name: broken, too
      shell: ls
      delegate_to: "{{ item }}"
      with_items:
        - aron.fritz.box
        - ben.fritz.box
    - name: broken, too
      shell: ls
      delegate_to: "{{ item }}"
      with_items:
        - aron.fritz.box
        - ben.fritz.box
